"use client";
import { useEffect, useRef, useState } from 'react';
import { Film, Upload, Link2, Download, Play, Pause, Scissors, SlidersHorizontal, Type, Layers, Settings2, Plus, X, Check, LoaderCircle, ArrowUpRight, FlipHorizontal2, RotateCcw, Volume2, Sparkles, FolderOpen, ChevronRight, MonitorPlay } from 'lucide-react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { defaults, Edit, exportVideo, paint, time } from '@/lib/video-editor';
type Clip = { id:string; name:string; url:string; source:'upload'|'network'; size?:number; duration:number; edit:Edit };
type Result = {name:string;url:string};
type Connections={apify:boolean;shotstack:boolean;supabase:boolean;localEditor:boolean};
const presets=[{id:'none',name:'Original',tag:'Só o essencial',color:'#687080'},{id:'clean',name:'Studio',tag:'Presença e respiro',color:'#a8be9d'},{id:'editorial',name:'Impacto',tag:'Feito para parar o scroll',color:'#ff7048'},{id:'paper',name:'Editorial',tag:'Uma nova perspectiva',color:'#ede4d2'}];
const settingsUrl='https://vercel.com/tropicalpote-bot/dex-videos-01/settings/environment-variables';
export default function Home(){
 const [clips,setClips]=useState<Clip[]>([]),[selected,setSelected]=useState(''),[tab,setTab]=useState('adjust'),[section,setSection]=useState('editor');
 const [connections,setConnections]=useState<Connections|null>(null),[connectOpen,setConnectOpen]=useState(false),[exportOpen,setExportOpen]=useState(false);
 const [url,setUrl]=useState(''),[limit,setLimit]=useState(20),[importing,setImporting]=useState(false),[busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[notice,setNotice]=useState(''),[playing,setPlaying]=useState(false),[position,setPosition]=useState(0),[results,setResults]=useState<Result[]>([]),[batch,setBatch]=useState(false);
 const [overlay,setOverlay]=useState<{url:string;type:string;name:string}|null>(null);
 const upload=useRef<HTMLInputElement>(null),overlayInput=useRef<HTMLInputElement>(null),video=useRef<HTMLVideoElement>(null),canvas=useRef<HTMLCanvasElement>(null),layer=useRef<HTMLImageElement|HTMLVideoElement|null>(null),abort=useRef<AbortController|null>(null),assets=useRef(new Set<string>()),importAbort=useRef<AbortController|null>(null);
 const active=clips.find(c=>c.id===selected)??clips[0];const edit=active?.edit??defaults;
 const liveEdit=useRef(edit);liveEdit.current=edit;
 const importSection=useRef<HTMLDivElement>(null);
 function keep(blob:Blob){const u=URL.createObjectURL(blob);assets.current.add(u);return u;}
 useEffect(()=>{void fetch('/api/connections').then(r=>r.json()).then(data=>setConnections(data as Connections)).catch(()=>setNotice('Não foi possível consultar as conexões.'));return()=>{abort.current?.abort();importAbort.current?.abort();assets.current.forEach(URL.revokeObjectURL);};},[]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(clips.length){e.preventDefault();}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[clips.length]);
 useEffect(()=>{let f=0;const tick=()=>{if(canvas.current&&video.current)paint(canvas.current,video.current,liveEdit.current,layer.current);f=requestAnimationFrame(tick);};tick();return()=>cancelAnimationFrame(f);},[]);
 useEffect(()=>{if(!overlay){layer.current=null;return;}const el=overlay.type==='video'?document.createElement('video'):new Image();el.src=overlay.url;layer.current=el;if(el instanceof HTMLVideoElement){el.loop=true;el.muted=true;void el.play().catch(()=>{});}return()=>{layer.current=null;if(el instanceof HTMLVideoElement){el.pause();el.removeAttribute('src');el.load();}};},[overlay]);
 useEffect(()=>{if(video.current){video.current.playbackRate=edit.speed;video.current.volume=edit.volume;}},[edit.speed,edit.volume,selected]);
 function patch(values:Partial<Edit>){if(!active)return;setClips(old=>old.map(c=>c.id===active.id?{...c,edit:{...c.edit,...values}}:c));}
 function addFiles(files:FileList|null){if(!files)return;const added=Array.from(files).filter(f=>f.type.startsWith('video/')).map(f=>({id:crypto.randomUUID(),name:f.name,url:keep(f),source:'upload' as const,size:f.size,duration:0,edit:{...defaults}}));if(!added.length)return setNotice('Selecione arquivos de vídeo MP4, MOV ou WebM.');setClips(old=>[...old,...added]);setSelected(added[0].id);setSection('editor');setNotice(`${added.length} arquivo(s) adicionado(s). Selecione um vídeo para editar.`);}
 function remove(id:string){const c=clips.find(x=>x.id===id);if(c?.url.startsWith('blob:')){URL.revokeObjectURL(c.url);assets.current.delete(c.url);}setClips(old=>old.filter(x=>x.id!==id));if(selected===id)setSelected('');}
 async function togglePlay(){const v=video.current;if(!v||!active)return;if(v.paused){if(v.currentTime>=edit.end||v.currentTime<edit.start)v.currentTime=edit.start;try{await v.play();}catch{setNotice('Não foi possível reproduzir. Tente enviar o arquivo original.');}}else v.pause();}
 async function importLink(){
  let parsed:URL;try{parsed=new URL(url);if(parsed.protocol!=='https:')throw 0;}catch{return setNotice('Cole um link HTTPS válido.');}
  const ctrl=new AbortController();importAbort.current=ctrl;setImporting(true);setNotice('Buscando seus vídeos…');
  try{
   if(/\.(mp4|webm|mov)$/i.test(parsed.pathname)){
    const response=await fetch(parsed.href,{signal:ctrl.signal});if(!response.ok)throw new Error('O link não está disponível.');
    if(Number(response.headers.get('content-length'))>250*1024*1024)throw new Error('Para arquivos maiores que 250 MB, baixe e use Enviar vídeos.');
    const reader=response.body?.getReader();if(!reader)throw new Error('Não foi possível baixar esse arquivo.');const pieces:Uint8Array<ArrayBuffer>[]=[];let bytes=0;
    while(true){const {done,value}=await reader.read();if(done)break;bytes+=value.length;if(bytes>250*1024*1024){await reader.cancel();throw new Error('Arquivo maior que 250 MB. Envie o vídeo do seu computador.');}pieces.push(value as Uint8Array<ArrayBuffer>);}
    const blob=new Blob(pieces,{type:response.headers.get('content-type')||'video/mp4'});const clip:Clip={id:crypto.randomUUID(),name:decodeURIComponent(parsed.pathname.split('/').pop()||'Vídeo importado'),url:keep(blob),source:'upload',size:blob.size,duration:0,edit:{...defaults}};setClips(old=>[...old,clip]);setSelected(clip.id);setSection('editor');setNotice('Vídeo importado. Pronto para editar.');return;
   }
   if(connections&&!connections.apify){setConnectOpen(true);throw new Error('Adicione APIFY_TOKEN na Vercel para importar perfis e Reels. Links diretos MP4/WebM e uploads já funcionam.');}
   const response=await fetch('/api/import/link',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:parsed.href,limit}),signal:ctrl.signal});const started=await response.json() as {error?:string;runId:string;datasetId:string;platform:string};if(!response.ok)throw new Error(started.error||'Falha ao iniciar importação.');
   let finished=false;
   for(let attempt=0;attempt<120;attempt++){
    await new Promise(r=>setTimeout(r,2500));if(ctrl.signal.aborted)throw new DOMException('Cancelado','AbortError');
    const q=new URLSearchParams({runId:started.runId,datasetId:started.datasetId,platform:started.platform,limit:String(limit)});
    const result=await fetch(`/api/import/link?${q}`,{signal:ctrl.signal,cache:'no-store'});const data=await result.json() as {error?:string;status:string;videos?:{name:string;url:string}[]};if(!result.ok)throw new Error(data.error||'Erro ao consultar vídeos.');
    if(data.status==='SUCCEEDED'){
     const added:Clip[]=(data.videos||[]).map((v:{name:string;url:string})=>({id:crypto.randomUUID(),name:v.name,url:v.url,source:'network',duration:0,edit:{...defaults}}));
     setClips(old=>[...old,...added.filter(c=>!old.some(x=>x.url===c.url))]);if(added[0])setSelected(added[0].id);
     setNotice(added.length?`${added.length} vídeos encontrados. Links de redes sociais podem expirar.`:'Nenhum vídeo público foi encontrado.');finished=true;
     if(added.length)void fetch('/api/batches',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sourceUrl:parsed.href,requestedCount:limit,importedCount:added.length,platform:started.platform})}).then(async r=>{const x=await r.json() as {saved:boolean};if(!x.saved)setNotice('Vídeos importados, mas o histórico não pôde ser salvo.');}).catch(()=>{});break;
    }
   }if(!finished)throw new Error('A busca excedeu 5 minutos. Confira a execução no Apify antes de iniciar outra.');
  }catch(e){setNotice(e instanceof Error&&e.name==='AbortError'?'Acompanhamento cancelado. A busca já iniciada pode continuar no Apify.':e instanceof TypeError?'O servidor do link bloqueou o download. Baixe o original e envie o arquivo.':e instanceof Error?e.message:'Falha na importação.');}finally{setImporting(false);importAbort.current=null;}
 }
 async function render(){if(!active)return;const ctrl=new AbortController();abort.current=ctrl;setBusy(true);setProgress(0);video.current?.pause();const targets=batch?clips:[active];let completed=0;
  try{for(const clip of targets){if(ctrl.signal.aborted)break;setNotice(`Exportando ${completed+1}/${targets.length}: ${clip.name}`);const {blob,extension}=await exportVideo(clip.url,clip.edit,overlay?.url,overlay?.type,p=>setProgress((completed+p/100)/targets.length*100),ctrl.signal);const name=`${clip.name.replace(/\.[^.]+$/,'')}-dex.${extension}`;setResults(old=>[...old,{name,url:keep(blob)}]);completed++;}setNotice(`${completed} vídeo(s) exportado(s). Os arquivos estão disponíveis para baixar.`);}catch(e){setNotice(e instanceof Error&&e.name==='AbortError'?`Exportação cancelada. ${completed} arquivo(s) concluído(s) preservado(s).`:e instanceof Error?e.message:'Falha ao exportar.');}finally{setBusy(false);abort.current=null;}
 }
 function applyAll(){setClips(old=>old.map(c=>({...c,edit:{...edit,start:c.edit.start,end:c.edit.end}})));setNotice('Visual, formato e ajustes aplicados a todos. Os cortes individuais foram preservados.');}
 function chooseSection(s:string){setSection(s);if(s==='connections')setConnectOpen(true);if(s==='templates')setTab('templates');if(s==='import')setTimeout(()=>importSection.current?.scrollIntoView({behavior:'smooth'}),20);}
 const duration=active?.duration||0;const selectedLength=Math.max(0,(edit.end||duration)-edit.start)/edit.speed;
 return <main className="studio">
  <aside className="rail"><a className="brand" href="#" aria-label="DeX Vídeo"><span><Film size={23}/></span><b>DeX<span> vídeo</span></b><small>STUDIO</small></a><div className="workspace-label">SEU ESPAÇO CRIATIVO</div><nav>{[{id:'editor',name:'Editor de vídeo',icon:MonitorPlay},{id:'import',name:'Importar vídeos',icon:Link2},{id:'templates',name:'Templates',icon:Layers},{id:'connections',name:'Conexões',icon:Settings2}].map(x=><button key={x.id} className={section===x.id?'active':''} onClick={()=>chooseSection(x.id)}><x.icon size={19}/>{x.name}{x.id==='editor'&&<span className="nav-dot"/>}</button>)}</nav><div className="rail-bottom"><div className="local-note"><span className="green-dot"/> Edição no seu navegador<p>Seu próximo vídeo começa aqui.</p></div><div className="profile"><span>EV</span><div><b>Everton</b><small>Meu estúdio</small></div><Settings2 size={17}/></div></div></aside>
  <div className="main-area"><header className="topbar"><div className="breadcrumb">Meu estúdio <ChevronRight size={14}/> <b>Editor</b></div><button className="quiet" onClick={()=>setConnectOpen(true)}><span className={connections?.apify?'green-dot':'amber-dot'}/>{connections?.apify?'Importador configurado':'Configurar importador'}<ArrowUpRight size={14}/></button></header>
   <div className="page-heading"><div><div className="eyebrow">MENOS REPETIÇÃO. MAIS CRIAÇÃO.</div><h1>Seu conteúdo, <span>outro nível.</span></h1><p>Importe, dê o seu toque e transforme ideias em vídeos.</p></div><button className="primary" onClick={()=>setExportOpen(true)} disabled={!active}><Download size={17}/> Exportar <span>{clips.length||0}</span></button></div>
   <div className="studio-grid">
    <section className="media-pane"><div className="pane-title"><h2>Biblioteca</h2><span>{clips.length} vídeos</span><button aria-label="Adicionar vídeos" onClick={()=>upload.current?.click()} disabled={busy}><Plus size={18}/></button></div>
     <input ref={upload} type="file" accept="video/*" multiple hidden onChange={e=>{addFiles(e.target.files);e.target.value='';}}/>
     <button className="drop-area" disabled={busy} onClick={()=>upload.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!busy)addFiles(e.dataTransfer.files);}}><span><Upload size={22}/></span><b>Enviar vídeos</b><small>Arraste aqui ou escolha arquivos</small><em>MP4 · MOV · WEBM</em></button>
     <div className="import-box" ref={importSection}><div className="label-line"><Link2 size={14}/> IMPORTAR POR LINK</div><input aria-label="Link do vídeo ou perfil" value={url} onChange={e=>setUrl(e.target.value)} placeholder="Cole um link de vídeo ou perfil" disabled={importing||busy}/><div className="import-options"><label>Quantidade<input aria-label="Quantidade de vídeos" type="number" min="1" max="500" value={limit} onChange={e=>setLimit(Math.min(500,Math.max(1,Math.floor(Number(e.target.value)||1))))}/></label><button className="secondary" onClick={importLink} disabled={importing||busy||!url}>{importing?<LoaderCircle className="spin" size={15}/>:<Plus size={15}/>}Importar</button></div>{importing&&<button className="text-button" onClick={()=>importAbort.current?.abort()}>Parar acompanhamento</button>}<small>Link direto: sem chave. Perfis e Reels: Apify.</small></div>
     <div className="library-heading">SEUS ARQUIVOS <span>{clips.length.toString().padStart(2,'0')}</span></div><div className="clip-list">{!clips.length?<div className="empty-library"><FolderOpen size={24}/><p>Uma biblioteca de possibilidades.<br/>Adicione seu primeiro vídeo.</p></div>:clips.map((c,i)=><div className={`clip ${active?.id===c.id?'selected':''}`} key={c.id}><button className="clip-select" disabled={busy} onClick={()=>{setSelected(c.id);setPlaying(false);setPosition(0);}}><span className="clip-thumb"><Film size={20}/><small>{String(i+1).padStart(2,'0')}</small></span><span><b>{c.name}</b><small>{c.duration?time(c.duration):c.source==='upload'?'Arquivo local':'Importado'}{c.size?` · ${(c.size/1048576).toFixed(1)} MB`:''}</small></span></button><button className="remove" disabled={busy} aria-label={`Remover ${c.name}`} onClick={()=>remove(c.id)}><X size={13}/></button></div>)}</div>
    </section>
    <section className="preview-pane"><div className="pane-title"><div className="label-line"><span className="green-dot"/> PRÉVIA AO VIVO</div><span>{edit.ratio} · 720p</span></div><div className="stage"><div className="stage-lines"/>{!active&&<div className="empty-stage"><div className="empty-film"><Film size={39}/></div><h2>O próximo vídeo é seu.</h2><p>Comece com um arquivo ou link.<br/>O resto acontece aqui.</p><button className="secondary" onClick={()=>upload.current?.click()}><Plus size={16}/> Adicionar vídeo</button><div className="empty-badges"><span>✦ Corte preciso</span><span>✦ Seu visual</span><span>✦ Exportação local</span></div></div>}<canvas ref={canvas} className={active?'preview-canvas':'preview-canvas hidden'} style={{aspectRatio:edit.ratio.replace(':','/')}}/>
     {active&&<video ref={video} key={active.id} src={active.url} crossOrigin="anonymous" playsInline preload="auto" className="source-video" onLoadedMetadata={e=>{e.currentTarget.playbackRate=edit.speed;e.currentTarget.volume=edit.volume;const d=e.currentTarget.duration;if(!Number.isFinite(d))return setNotice('Não foi possível determinar a duração. Envie um arquivo local.');setClips(old=>old.map(c=>c.id===active.id?{...c,duration:d,edit:{...c.edit,end:c.edit.end||d}}:c));}} onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onError={()=>setNotice('Este vídeo não carregou. O link pode ter expirado ou bloqueado a reprodução; envie o arquivo original.')} onTimeUpdate={e=>{setPosition(e.currentTarget.currentTime);if(edit.end&&e.currentTarget.currentTime>=edit.end){e.currentTarget.pause();}}}/>}</div>
     <div className="transport"><span>{time(position)} <i>/ {time(duration)}</i></span><button className="play" disabled={!active||busy} onClick={togglePlay} aria-label={playing?'Pausar':'Reproduzir'}>{playing?<Pause size={18}/>:<Play size={18} fill="currentColor"/>}</button><span><Volume2 size={15}/> {Math.round(edit.volume*100)}%</span></div>
     <div className="timeline"><div className="timeline-top"><b><Scissors size={14}/> Linha do tempo</b><small>{time(selectedLength)} de saída</small></div><input aria-label="Posição de reprodução" className="scrubber" type="range" min={0} max={duration||1} step={.05} value={position} disabled={!active||busy} onChange={e=>{if(video.current)video.current.currentTime=Number(e.target.value);setPosition(Number(e.target.value));}}/><div className="timeline-track"><Film size={16}/><span>{active?.name||'Seu vídeo aparecerá aqui'}</span><i style={{left:`${duration?edit.start/duration*100:0}%`,width:`${duration?(edit.end-edit.start)/duration*100:100}%`}}/></div><div className="time-labels"><span>00:00</span><span>{time(duration/2)}</span><span>{time(duration)}</span></div></div>
    </section>
    <section className="inspector"><div className="tool-tabs" role="tablist" aria-label="Ferramentas">{[{id:'adjust',icon:SlidersHorizontal,label:'Ajustes'},{id:'text',icon:Type,label:'Texto'},{id:'templates',icon:Layers,label:'Templates'}].map(x=><button key={x.id} role="tab" aria-selected={tab===x.id} onClick={()=>setTab(x.id)} className={tab===x.id?'active':''}><x.icon size={17}/>{x.label}</button>)}</div><fieldset disabled={!active||busy} className="controls">
     {tab==='adjust'&&<><div className="control-heading"><h3>O enquadramento certo.</h3><p>Um vídeo, todos os formatos.</p></div><label>FORMATO</label><div className="ratio-options">{['9:16','1:1','16:9'].map(r=><button className={edit.ratio===r?'selected':''} key={r} onClick={()=>patch({ratio:r})}><span className={'ratio-icon r'+r.replace(':','')}/>{r}</button>)}</div><div className="split-control"><label>Ajuste da imagem<select value={edit.fit} onChange={e=>patch({fit:e.target.value})}><option value="contain">Mostrar inteiro</option><option value="cover">Preencher quadro</option></select></label><button className={edit.flip?'selected icon-button':'icon-button'} onClick={()=>patch({flip:!edit.flip})} aria-label="Espelhar horizontalmente"><FlipHorizontal2 size={18}/></button></div><div className="control-divider"/><label>CORTE DO VÍDEO</label><div className="cut-fields"><label>Início (segundos)<input type="number" step="0.1" min="0" max={Math.max(0,edit.end-.1)} value={Number(edit.start.toFixed(2))} onChange={e=>patch({start:Math.max(0,Math.min(Number(e.target.value),edit.end-.1))})}/></label><label>Fim (segundos)<input type="number" step="0.1" min={edit.start+.1} max={duration||1} value={Number(edit.end.toFixed(2))} onChange={e=>patch({end:Math.min(duration,Math.max(edit.start+.1,Number(e.target.value)))})}/></label></div><label className="select-label">Velocidade<select value={edit.speed} onChange={e=>patch({speed:Number(e.target.value)})}>{[.5,.75,1,1.25,1.5,2].map(n=><option key={n} value={n}>{n}×</option>)}</select></label><div className="control-divider"/>{[{key:'volume',name:'Volume',max:1,min:0,step:.01},{key:'brightness',name:'Brilho',min:0,max:200,step:1},{key:'contrast',name:'Contraste',min:0,max:200,step:1},{key:'saturation',name:'Saturação',min:0,max:200,step:1}].map(x=><label className="range-control" key={x.key}><span>{x.name}<b>{Math.round(Number(edit[x.key as keyof Edit])*(x.key==='volume'?100:1))}%</b></span><input type="range" min={x.min} max={x.max} step={x.step} value={Number(edit[x.key as keyof Edit])} onChange={e=>patch({[x.key]:Number(e.target.value)})}/></label>)}</>}
     {tab==='text'&&<><div className="control-heading"><h3>Palavras que ficam.</h3><p>Seu título e sua chamada no vídeo.</p></div><label className="text-field">Título<textarea value={edit.title} maxLength={100} placeholder="Uma ideia que merece ser vista." onChange={e=>patch({title:e.target.value})}/><small>{edit.title.length}/100</small></label><label className="text-field">Chamada final<input value={edit.footer} maxLength={60} placeholder="Siga para mais" onChange={e=>patch({footer:e.target.value})}/></label><label className="color-control">Cor de destaque<input aria-label="Cor de destaque" type="color" value={edit.accent} onChange={e=>patch({accent:e.target.value})}/><span>{edit.accent}</span></label><p className="hint">Os textos fazem parte do arquivo exportado. Deixe os campos vazios para um visual sem texto.</p></>}
     {tab==='templates'&&<><div className="control-heading"><h3>Encontre o seu visual.</h3><p>Molduras que valorizam o conteúdo.</p></div><div className="preset-grid">{presets.map(p=><button className={edit.template===p.id?'selected':''} key={p.id} onClick={()=>patch({template:p.id})}><div className={'preset-art '+p.id} style={{'--preset':p.color} as React.CSSProperties}><span/><i/><b>DeX</b></div><strong>{p.name}</strong><small>{p.tag}</small>{edit.template===p.id&&<Check size={13}/>}</button>)}</div><input ref={overlayInput} type="file" accept="image/png,image/webp,video/mp4" hidden onChange={e=>{const f=e.target.files?.[0];if(f){if(overlay)URL.revokeObjectURL(overlay.url);setOverlay({url:keep(f),name:f.name,type:f.type.startsWith('video/')?'video':'image'});}e.target.value='';}}/><button className="overlay-upload" onClick={()=>overlayInput.current?.click()}><Upload size={18}/><span>{overlay?.name||'Sua própria moldura'}<small>PNG, WebP ou MP4 · aplicada ao lote</small></span></button>{overlay&&<button className="text-button" onClick={()=>setOverlay(null)}>Remover moldura</button>}</>}
     <div className="control-divider"/><button className="apply-all" onClick={applyAll}><Layers size={16}/> Aplicar visual ao lote</button><button className="reset" onClick={()=>patch({...defaults,end:duration})}><RotateCcw size={13}/> Redefinir este vídeo</button></fieldset>{!active&&<div className="inspector-hint"><Sparkles size={16}/> Adicione um vídeo para liberar os controles.</div>}</section>
   </div><footer className="studio-footer"><span><Check size={14}/> Prévia e exportação usam o mesmo visual</span><span>Arquivos locais ficam no seu dispositivo · mantenha a aba aberta ao exportar</span></footer>
  </div>
  <Dialog open={connectOpen} onOpenChange={setConnectOpen}><DialogContent className="studio-dialog"><DialogHeader><DialogTitle>Conexões do estúdio</DialogTitle><DialogDescription>Veja o que já está disponível e o que precisa configurar.</DialogDescription></DialogHeader><div className="connection-cards">{[{name:'Editor e exportação local',ready:true,desc:'Cortes, textos, ajustes e download no navegador.'},{name:'Apify · Instagram e Facebook',ready:connections?.apify,desc:'Importação de perfis e Reels públicos. Requer APIFY_TOKEN.'},{name:'Shotstack · Renderização em nuvem',ready:connections?.shotstack,desc:'Motor legado para lotes remotos. Requer SHOTSTACK_API_KEY.'},{name:'Supabase · Histórico de lotes',ready:connections?.supabase,desc:'Registra os lotes importados. Não representa login ou armazenamento de arquivos.'}].map(x=><div key={x.name}><span className={x.ready?'green-dot':'amber-dot'}/><div><b>{x.name}</b><p>{x.desc}</p><small>{x.ready?'Configurado':connections?'Pendente':'Verificando…'}</small></div></div>)}</div><a className="primary" href={settingsUrl} target="_blank" rel="noreferrer">Configurar chaves na Vercel <ArrowUpRight size={16}/></a><p className="hint">Salve as chaves como variáveis de ambiente e faça um novo deploy. Não envie senhas aqui. Publicação automática na Meta ainda não está conectada.</p></DialogContent></Dialog>
  <Dialog open={exportOpen} onOpenChange={v=>{if(!busy)setExportOpen(v);}}><DialogContent className="studio-dialog"><DialogHeader><DialogTitle>Pronto para sair do estúdio.</DialogTitle><DialogDescription>Exportação local com seu corte, áudio, textos e visual aplicados.</DialogDescription></DialogHeader><div className="export-summary"><Film size={26}/><div><b>{batch?`${clips.length} vídeos`:active?.name||'Nenhum vídeo'}</b><p>720p · 30 fps · MP4 ou WebM, conforme o navegador</p></div></div><label className="checkbox"><input type="checkbox" checked={batch} disabled={busy} onChange={e=>setBatch(e.target.checked)}/> Exportar todos os vídeos da biblioteca</label><p className="hint">O processamento acompanha a duração do vídeo. Mantenha esta aba visível. Os arquivos exportados são recriados; os metadados do original não são copiados. Não recarregue antes de baixar.</p>{busy?<><progress max="100" value={progress}/><p>{Math.round(progress)}% concluído</p><button className="secondary" onClick={()=>abort.current?.abort()}>Cancelar exportação</button></>:<button className="primary" disabled={!active} onClick={render}><Download size={17}/> Exportar {batch?'lote':'vídeo'}</button>}<div className="result-list">{results.map(r=><a key={r.url} href={r.url} download={r.name}><Check size={16}/><span>{r.name}</span><Download size={16}/></a>)}</div></DialogContent></Dialog>
  {notice&&<div className="notification" role="status"><span>{notice}</span><button aria-label="Fechar mensagem" onClick={()=>setNotice('')}><X size={16}/></button></div>}
 </main>;
}
